version: "3.9"
services:
  frontend:
    image: ghcr.io/linoleparquet/lior-frontend:master
    ports:
      - "80:80"
  bakckend:
    image: ghcr.io/linoleparquet/lior-backend:master
    ports:
      - "8080:8080"