apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |-
    server {
        listen 80;
        root /usr/share/nginx/html;

        location /api {
            proxy_pass http://{{ include "lior.fullname" . }}-backend:8080/;
        }
    }
